version: '3.4'

services:
  service:
    image: opendentity/service 
    ports:
      - 8080:80
    environment:
        ASPNETCORE_ENVIRONMENT: "Docker"
    build:
      context: .
      dockerfile: src/Opendentity.Service/Dockerfile

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: opendentity
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes --requirepass secret

  pgadmin:
    image: dpage/pgadmin4:5.1
    ports:
      - 8010:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@opendentity.io
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmindata:/var/lib/pgadmin

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379:0:secret

volumes:
  postgresdata:
  pgadmindata:
  redisdata: