version: '3.4'

services:
  tests: 
    image: opendentity/tests
    build:
     context: .
     dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      BASE_URL: http://service
    depends_on:
      - service
      - postgres
    volumes:
      - ./outputs:/test/outputs

  service:
   image: opendentity/service 
   environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
   build:
     context: ../
     dockerfile: src/Opendentity.Service/Dockerfile

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: opendentity
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
